#!/usr/bin/env Rscript

Uses the docker image rocker/tidyverse:4.2

```{r load packages needed}
library(tidyverse)
library(stringr)
library(data.table)
library(collections)

kegg_gene_names <- dict()

kegg_gene <- read_table("../data/huang-2018/02.gene.annotation/CGM-RGC.KEGG.gene.stat")

kegg_gene$ListOfKOs <- str_sub(kegg_gene$ListOfKOs, end=-2)

keggs_of_interest <- read.table("../data/nitrogen-degradation-kegg-pathways.csv",sep=',',header = T)

kegg_abundance <- read_table("../data/huang-2018/03.profiles/02.relative.KEGG.abundance/CGM-RGC.gene.abundance.xls.KEGG.KO.ratio")

selected <- kegg_abundance[ kegg_abundance$"#KEGG" %in% keggs_of_interest$orthology,]

selected_gene_tab <- kegg_gene[kegg_gene$ListOfKOs %in% selected$"#KEGG", ]

#TODO need to select rows ListOfKOs and kegg_gene specifically so we can work with it
for (i in 1:length(selected_gene_tab$ListOfKOs)){
    curr_kegg <- selected_gene_tab$ListOfKOs[i]
    curr_gene <- selected_gene_tab$kegg_gene[i]

    tryCatch({
        prev_genes <- kegg_gene_names$get(curr_kegg)
        current_genes <- append(prev_genes, curr_gene)
        kegg_gene_names$set(curr_kegg, current_genes)
    }, error= function(e) {
        kegg_gene_names$set(curr_kegg,c(curr_gene))
    }
    )
}

kegg_gene_name_list <- kegg_gene_names$as_list()

more_info <- data.frame()

for (i in 1:length(selected$"#KEGG")){
    curr_kegg <- selected$"#KEGG"[i]
    curr_row <- selected[i,]
    curr_genes <- kegg_gene_name_list[[curr_kegg]]
    freq <- data.frame(table(factor(curr_genes)))
    freq <- freq[order(freq$Freq,decreasing=T),]
    curr_genes <- paste(apply(freq, 1, paste0, collapse=":"),collapse=';')
    curr_row$genes <- curr_genes
    #curr_row$genes <- paste(curr_genes, collapse=";")
    more_info <- rbind(more_info, curr_row)
}

#more_info <- tibble(more_info)

write_tsv(more_info,"../data/huang-analysis/kegg-gene-abundance-nitrogen-abundance.tsv")
```

```{r duodenum average kegg abundances}
library(tidyverse)


#select just gene names from kegg table so we can join on them later

kegg_tab <- read_table("../data/huang-analysis/kegg-gene-abundance-nitrogen-abundance.tsv")

#select cols with ceca in the 5th english letter

duo_samp <- kegg_tab[,str_sub(colnames(kegg_tab),5,5) == "D"]

n_samp <- dim(duo_samp)[2]

abund <- rowSums(duo_samp)

abund <- abund/n_samp

duo_average_table <- cbind(kegg_tab$"#KEGG",abund, kegg_tab$genes)

duo_average_df <- data.frame(duo_average_table)
colnames(duo_average_df) <- c("kegg", "rabundance", "kegggenes")


duo_average_df <- duo_average_df[order(as.numeric(duo_average_df$rabundance),decreasing=T),]


write_tsv(duo_average_df,"../data/huang-analysis/duo-average-gene-abundance.tsv")
```

```{r jejunum subset kegg abundances}

library(tidyverse)


#select just gene names from kegg table so we can join on them later

kegg_tab <- read_table("../data/huang-analysis/kegg-gene-abundance-nitrogen-abundance.tsv")

#select cols with ceca in the 5th english letter

jeju_samp <- kegg_tab[,str_sub(colnames(kegg_tab),5,5) == "J"]

n_samp <- dim(jeju_samp)[2]

abund <- rowSums(jeju_samp)

abund <- abund/n_samp

jeju_average_table <- cbind(kegg_tab$"#KEGG",abund, kegg_tab$genes)

jeju_average_df <- data.frame(jeju_average_table)
colnames(jeju_average_df) <- c("kegg", "rabundance", "kegggenes")

jeju_average_df <- jeju_average_df[order(as.numeric(jeju_average_df$rabundance),decreasing=T),]


write_tsv(jeju_average_df,"../data/huang-analysis/jeju-average-gene-abundance.tsv")
```

```{r ileum subset keggs}
library(tidyverse)


#select just gene names from kegg table so we can join on them later

kegg_tab <- read_table("../data/huang-analysis/kegg-gene-abundance-nitrogen-abundance.tsv")

#select cols with ceca in the 5th english letter

ileum_samp <- kegg_tab[,str_sub(colnames(kegg_tab),5,5) == "I"]

n_samp <- dim(ileum_samp)[2]

abund <- rowSums(ileum_samp)

abund <- abund/n_samp

ileum_average_table <- cbind(kegg_tab$"#KEGG",abund, kegg_tab$genes)

ileum_average_df <- data.frame(ileum_average_table)
colnames(ileum_average_df) <- c("kegg", "rabundance", "kegggenes")

ileum_average_df <- ileum_average_df[order(as.numeric(ileum_average_df$rabundance),decreasing=T),]

write_tsv(ileum_average_df,"../data/huang-analysis/ileum-average-gene-abundance.tsv")
```

```{r colorectum subset keggs}
library(tidyverse)


#select just gene names from kegg table so we can join on them later

kegg_tab <- read_table("../data/huang-analysis/kegg-gene-abundance-nitrogen-abundance.tsv")

#select cols with ceca in the 5th english letter

rect_samp <- kegg_tab[,str_sub(colnames(kegg_tab),5,5) == "R"]

n_samp <- dim(rect_samp)[2]

abund <- rowSums(rect_samp)

abund <- abund/n_samp

rect_average_table <- cbind(kegg_tab$"#KEGG",abund, kegg_tab$genes)

rect_average_df <- data.frame(rect_average_table)
colnames(rect_average_df) <- c("kegg", "rabundance", "kegggenes")

rect_average_df <- rect_average_df[order(as.numeric(rect_average_df$rabundance),decreasing=T),]

write_tsv(rect_average_df,"../data/huang-analysis/rect-average-gene-abundance.tsv")
```

```{r ceca subset keggs}
library(tidyverse)


#select just gene names from kegg table so we can join on them later

kegg_tab <- read_table("../data/huang-analysis/kegg-gene-abundance-nitrogen-abundance.tsv")

#select cols with ceca in the 5th english letter

ceca_samp <- kegg_tab[,str_sub(colnames(kegg_tab),5,5) == "C"]

n_samp <- dim(ceca_samp)[2]

abund <- rowSums(ceca_samp)

abund <- abund/n_samp

ceca_average_table <- cbind(kegg_tab$"#KEGG",abund, kegg_tab$genes)

ceca_average_df <- data.frame(ceca_average_table)
colnames(ceca_average_df) <- c("kegg", "rabundance", "kegggenes")
ceca_average_df <- ceca_average_df[order(as.numeric(ceca_average_df$rabundance),decreasing=T),]

write_tsv(ceca_average_df,"../data/huang-analysis/ceca-average-gene-abundance.tsv")
```

```{r function to collapse average relative abundance}

collapse_rabund <- function(abundance_tab, tissue){
    samp <- abundance_tab[,str_sub(colnames(abundance_tab),5,5) == tissue]
    n_samp <- dim(samp)[2]
    abund <- rowSums(samp)
    abund <- abund/n_samp
    average_table <- cbind(abundance_tab$"#KEGG",abund)
    average_df <- data.frame(average_table)
    colnames(average_df) <- c("kegg", "rabundance")
    average_df <- average_df[order(as.numeric(average_df$rabundance),decreasing=T),]
    return(average_df)
}

# Take in a column of average relative abundance, and a list of keggs

generate_kegg_gene_list <- function(kegg_abundance, pathway_table, kegg_gene ){

    selected <- kegg_abundance[ kegg_abundance$kegg %in% pathway_table$orthology,]
    selected_gene <- kegg_gene[kegg_gene$ListOfKOs %in% selected$kegg, ]
    kegg_gene_names <- dict()

    for (i in 1:length(selected_gene$ListOfKOs)){
        curr_kegg <- selected_gene$ListOfKOs[i]
        curr_gene <- selected_gene$kegg_gene[i]

        tryCatch({
            prev_genes <- kegg_gene_names$get(curr_kegg)
            current_genes <- append(prev_genes, curr_gene)
            kegg_gene_names$set(curr_kegg, current_genes)
        }, error= function(e) {
            kegg_gene_names$set(curr_kegg,c(curr_gene))
        }
        )
    }

    kegg_gene_name_list <- kegg_gene_names$as_list()
    return(list(selected, kegg_gene_name_list))
}

generate_more_info_table <- function(selected, kegg_gene_name_list, filepath){
    more_info <- data.frame()

    for (i in 1:length(selected$kegg)){
        curr_kegg <- selected$kegg[i]
        curr_row <- selected[i,]
        curr_genes <- kegg_gene_name_list[[1]][[curr_kegg]]
        freq <- data.frame(table(factor(curr_genes)))
        freq <- freq[order(freq$Freq,decreasing=T),]
        curr_genes <- paste(apply(freq, 1, paste0, collapse=":"),collapse=';')
        curr_row$genes <- curr_genes
        #curr_row$genes <- paste(curr_genes, collapse=";")
        more_info <- rbind(more_info, curr_row)
    }

    write_tsv(more_info,filepath)
    return(more_info)
}



```

```{r rebuild table again}
library(tidyverse)
library(stringr)
library(data.table)
library(collections)

kegg_gene_raw <- read_table("../data/huang-2018/02.gene.annotation/CGM-RGC.KEGG.gene.stat")

#kegg_gene <- kegg_gene_raw
kegg_gene_raw$ListOfKOs <- str_sub(kegg_gene_raw$ListOfKOs, end=-2)

keggs_of_interest <- read.table("../data/nitrogen-degradation-kegg-pathways.csv",sep=',',header = T)

kegg_abundance <- read_table("../data/huang-2018/03.profiles/02.relative.KEGG.abundance/CGM-RGC.gene.abundance.xls.KEGG.KO.ratio")

# separate out samples by tissue

duo_average_df <- collapse_rabund(kegg_abundance, "D")
jejunum_average_df <- collapse_rabund(kegg_abundance,"J")
ileum_average_df <- collapse_rabund(kegg_abundance,"I")
ceca_average_df <- collapse_rabund(kegg_abundance, "C")
rectum_average_df <- collapse_rabund(kegg_abundance, "R")

# TODO do we need to do this? merge columns into table
merge_1 <- merge(duo_average_df, jejunum_average_df,by='kegg')
colnames(merge_1) <- c('kegg','duodenum','jejunum')
merge_2 <- merge(merge_1, ileum_average_df,by='kegg')
colnames(merge_2) <- c('kegg','duodenum','jejunum','ileum')
merge_3 <- merge(merge_2, ceca_average_df,by='kegg')
colnames(merge_3) <- c('kegg','duodenum','jejunum','ileum','ceca')
merge_4 <- merge(merge_3, rectum_average_df,by='kegg')
colnames(merge_4) <- c('kegg','duodenum','jejunum','ileum','ceca','rectum')

# separate pathways out so that pathway to pathway comparisons can be done
protein_digestion_and_absorption <- keggs_of_interest[keggs_of_interest$name == "Protein digestion and absorption",]
gastric_acid_secretion <-  keggs_of_interest[keggs_of_interest$name == "Gastric acid secretion",]
pancreatic_acid_secretion <- keggs_of_interest[keggs_of_interest$name == "Pancreatic secretion",]
valine_leucine_isoleucine <- keggs_of_interest[keggs_of_interest$name == "Valine; leucine and isoleucine degradation",]
tyrosine_metabolism <- keggs_of_interest[keggs_of_interest$name == "Tyrosine metabolism",]
tryptophan_metabolism <- keggs_of_interest[keggs_of_interest$name == "Tryptophan metabolism",]
alanine_aspartate_glutamate <- keggs_of_interest[keggs_of_interest$name == "Alanine; aspartate and glutamate metabolism",]
nitrogen_metabolism <- keggs_of_interest[keggs_of_interest$name == "Nitrogen metabolism",]


```

```{r duodenum analysis}
duo_protein_gene_list <- generate_kegg_gene_list(duo_average_df, protein_digestion_and_absorption, kegg_gene_raw)
duo_protein_more_info <- generate_more_info_table(data.frame(duo_protein_gene_list[1]),duo_protein_gene_list[2],"../data/huang-analysis/duo-protein-digestion-and-absorption.tsv")

duo_gastric_gene_list <- generate_kegg_gene_list(duo_average_df, gastric_acid_secretion, kegg_gene_raw)
duo_gastric_more_info <- generate_more_info_table(data.frame(duo_gastric_gene_list[1]),duo_gastric_gene_list[2],"../data/huang-analysis/duo-gastric-acid-secretion.tsv")

duo_pancreatic_acid_gene_list <- generate_kegg_gene_list(duo_average_df, pancreatic_acid_secretion, kegg_gene_raw)
duo_pancreatic_more_info <- generate_more_info_table(data.frame(duo_pancreatic_acid_gene_list[1]),duo_pancreatic_acid_gene_list[2],"../data/huang-analysis/duo-pancreatic-acid-secretion.tsv")

duo_valine_gene_list <- generate_kegg_gene_list(duo_average_df, valine_leucine_isoleucine, kegg_gene_raw)
duo_valine_more_info <- generate_more_info_table(data.frame(duo_valine_gene_list[1]),duo_valine_gene_list[2],"../data/huang-analysis/duo-valine-leucine-isoleucine.tsv")

duo_tyrosine_gene_list <- generate_kegg_gene_list(duo_average_df, tyrosine_metabolism, kegg_gene_raw)
duo_tyrosine_more_info <- generate_more_info_table(data.frame(duo_tyrosine_gene_list[1]),duo_tyrosine_gene_list[2],"../data/huang-analysis/duo-tyrosine-metabolism.tsv")

duo_tryptophan_gene_list <- generate_kegg_gene_list(duo_average_df, tryptophan_metabolism , kegg_gene_raw)
duo_tryptophan_more_info <- generate_more_info_table(data.frame(duo_tryptophan_gene_list[1]),duo_tryptophan_gene_list[2],"../data/huang-analysis/duo-tryptophan-metabolism.tsv")

duo_alanine_gene_list <- generate_kegg_gene_list(duo_average_df, alanine_aspartate_glutamate, kegg_gene_raw)
duo_alanine_more_info <- generate_more_info_table(data.frame(duo_alanine_gene_list[1]),duo_alanine_gene_list[2],"../data/huang-analysis/duo-alanine-aspartate-glutamate.tsv")

duo_nitrogen_gene_list <- generate_kegg_gene_list(duo_average_df, nitrogen_metabolism, kegg_gene_raw)
duo_nitrogen_more_info <- generate_more_info_table(data.frame(duo_nitrogen_gene_list[1]),duo_nitrogen_gene_list[2],"../data/huang-analysis/duo-nitrogen-metabolism.tsv")
```

```{r jejunum analysis}
jejunum_protein_gene_list <- generate_kegg_gene_list(jejunum_average_df, protein_digestion_and_absorption, kegg_gene_raw)
jejunum_protein_more_info <- generate_more_info_table(data.frame(jejunum_protein_gene_list[1]),jejunum_protein_gene_list[2],"../data/huang-analysis/jejunum-protein-digestion-and-absorption.tsv")

jejunum_gastric_gene_list <- generate_kegg_gene_list(jejunum_average_df, gastric_acid_secretion, kegg_gene_raw)
jejunum_gastric_more_info <- generate_more_info_table(data.frame(jejunum_gastric_gene_list[1]),jejunum_gastric_gene_list[2],"../data/huang-analysis/jejunum-gastric-acid-secretion.tsv")

jejunum_pancreatic_acid_gene_list <- generate_kegg_gene_list(jejunum_average_df, pancreatic_acid_secretion, kegg_gene_raw)
jejunum_pancreatic_more_info <- generate_more_info_table(data.frame(jejunum_pancreatic_acid_gene_list[1]),jejunum_pancreatic_acid_gene_list[2],"../data/huang-analysis/jejunum-pancreatic-acid-secretion.tsv")

jejunum_valine_gene_list <- generate_kegg_gene_list(jejunum_average_df, valine_leucine_isoleucine, kegg_gene_raw)
jejunum_valine_more_info <- generate_more_info_table(data.frame(jejunum_valine_gene_list[1]),jejunum_valine_gene_list[2],"../data/huang-analysis/jejunum-valine-leucine-isoleucine.tsv")

jejunum_tyrosine_gene_list <- generate_kegg_gene_list(jejunum_average_df, tyrosine_metabolism, kegg_gene_raw)
jejunum_tyrosine_more_info <- generate_more_info_table(data.frame(jejunum_tyrosine_gene_list[1]),jejunum_tyrosine_gene_list[2],"../data/huang-analysis/jejunum-tyrosine-metabolism.tsv")

jejunum_tryptophan_gene_list <- generate_kegg_gene_list(jejunum_average_df, tryptophan_metabolism , kegg_gene_raw)
jejunum_tryptophan_more_info <- generate_more_info_table(data.frame(jejunum_tryptophan_gene_list[1]),jejunum_tryptophan_gene_list[2],"../data/huang-analysis/jejunum-tryptophan-metabolism.tsv")

jejunum_alanine_gene_list <- generate_kegg_gene_list(jejunum_average_df, alanine_aspartate_glutamate , kegg_gene_raw)
jejunum_alanine_more_info <- generate_more_info_table(data.frame(jejunum_alanine_gene_list[1]),jejunum_alanine_gene_list[2],"../data/huang-analysis/jejunum-alanine-aspartate-glutamate.tsv")

jejunum_nitrogen_gene_list <- generate_kegg_gene_list(jejunum_average_df, nitrogen_metabolism, kegg_gene_raw)
jejunum_nitrogen_more_info <- generate_more_info_table(data.frame(jejunum_nitrogen_gene_list[1]),jejunum_nitrogen_gene_list[2],"../data/huang-analysis/jejunum-nitrogen-metabolism.tsv")
```

```{r ileum analysis}
ileum_protein_gene_list <- generate_kegg_gene_list(ileum_average_df, protein_digestion_and_absorption, kegg_gene_raw)
ileum_protein_more_info <- generate_more_info_table(data.frame(ileum_protein_gene_list[1]),ileum_protein_gene_list[2],"../data/huang-analysis/ileum-protein-digestion-and-absorption.tsv")

ileum_gastric_gene_list <- generate_kegg_gene_list(ileum_average_df, gastric_acid_secretion, kegg_gene_raw)
ileum_gastric_more_info <- generate_more_info_table(data.frame(ileum_gastric_gene_list[1]),ileum_gastric_gene_list[2],"../data/huang-analysis/ileum-gastric-acid-secretion.tsv")

ileum_pancreatic_acid_gene_list <- generate_kegg_gene_list(ileum_average_df, pancreatic_acid_secretion, kegg_gene_raw)
ileum_pancreatic_more_info <- generate_more_info_table(data.frame(ileum_pancreatic_acid_gene_list[1]),ileum_pancreatic_acid_gene_list[2],"../data/huang-analysis/ileum-pancreatic-acid-secretion.tsv")

ileum_valine_gene_list <- generate_kegg_gene_list(ileum_average_df, valine_leucine_isoleucine, kegg_gene_raw)
ileum_valine_more_info <- generate_more_info_table(data.frame(ileum_valine_gene_list[1]),ileum_valine_gene_list[2],"../data/huang-analysis/ileum-valine-leucine-isoleucine.tsv")

ileum_tyrosine_gene_list <- generate_kegg_gene_list(ileum_average_df, tyrosine_metabolism, kegg_gene_raw)
ileum_tyrosine_more_info <- generate_more_info_table(data.frame(ileum_tyrosine_gene_list[1]),ileum_tyrosine_gene_list[2],"../data/huang-analysis/ileum-tyrosine-metabolism.tsv")

ileum_tryptophan_gene_list <- generate_kegg_gene_list(ileum_average_df, tryptophan_metabolism , kegg_gene_raw)
ileum_tryptophan_more_info <- generate_more_info_table(data.frame(ileum_tryptophan_gene_list[1]),ileum_tryptophan_gene_list[2],"../data/huang-analysis/ileum-tryptophan-metabolism.tsv")

ileum_alanine_gene_list <- generate_kegg_gene_list(ileum_average_df, alanine_aspartate_glutamate , kegg_gene_raw)
ileum_alanine_more_info <- generate_more_info_table(data.frame(ileum_alanine_gene_list[1]),ileum_alanine_gene_list[2],"../data/huang-analysis/ileum-alanine-aspartate-glutamate.tsv")

ileum_nitrogen_gene_list <- generate_kegg_gene_list(ileum_average_df, nitrogen_metabolism, kegg_gene_raw)
ileum_nitrogen_more_info <- generate_more_info_table(data.frame(ileum_nitrogen_gene_list[1]),ileum_nitrogen_gene_list[2],"../data/huang-analysis/ileum-nitrogen-metabolism.tsv")
```

```{r ceca analysis}
ceca_protein_gene_list <- generate_kegg_gene_list(ceca_average_df, protein_digestion_and_absorption, kegg_gene_raw)
ceca_protein_more_info <- generate_more_info_table(data.frame(ceca_protein_gene_list[1]),ceca_protein_gene_list[2],"../data/huang-analysis/ceca-protein-digestion-and-absorption.tsv")

ceca_gastric_gene_list <- generate_kegg_gene_list(ceca_average_df, gastric_acid_secretion, kegg_gene_raw)
ceca_gastric_more_info <- generate_more_info_table(data.frame(ceca_gastric_gene_list[1]),ceca_gastric_gene_list[2],"../data/huang-analysis/ceca-gastric-acid-secretion.tsv")

ceca_pancreatic_acid_gene_list <- generate_kegg_gene_list(ceca_average_df,  pancreatic_acid_secretion, kegg_gene_raw)
ceca_pancreatic_more_info <- generate_more_info_table(data.frame(ceca_pancreatic_acid_gene_list[1]),ceca_pancreatic_acid_gene_list[2],"../data/huang-analysis/ceca-pancreatic-acid-secretion.tsv")

ceca_valine_gene_list <- generate_kegg_gene_list(ceca_average_df,  valine_leucine_isoleucine, kegg_gene_raw)
ceca_valine_more_info <- generate_more_info_table(data.frame(ceca_valine_gene_list[1]),ceca_valine_gene_list[2],"../data/huang-analysis/ceca-valine-leucine-isoleucine.tsv")

ceca_tyrosine_gene_list <- generate_kegg_gene_list(ceca_average_df,  tyrosine_metabolism, kegg_gene_raw)
ceca_tyrosine_more_info <- generate_more_info_table(data.frame(ceca_tyrosine_gene_list[1]),ceca_tyrosine_gene_list[2],"../data/huang-analysis/ceca-tyrosine-metabolism.tsv")

ceca_tryptophan_gene_list <- generate_kegg_gene_list(ceca_average_df, tryptophan_metabolism , kegg_gene_raw)
ceca_tryptophan_more_info <- generate_more_info_table(data.frame(ceca_tryptophan_gene_list[1]),ceca_tryptophan_gene_list[2],"../data/huang-analysis/ceca-tryptophan-metabolism.tsv")

ceca_alanine_gene_list <- generate_kegg_gene_list(ceca_average_df, alanine_aspartate_glutamate , kegg_gene_raw)
ceca_alanine_more_info <- generate_more_info_table(data.frame(ceca_alanine_gene_list[1]),ceca_alanine_gene_list[2],"../data/huang-analysis/ceca-alanine-aspartate-glutamate.tsv")

ceca_nitrogen_gene_list <- generate_kegg_gene_list(ceca_average_df, nitrogen_metabolism, kegg_gene_raw)
ceca_nitrogen_more_info <- generate_more_info_table(data.frame(ceca_nitrogen_gene_list[1]),ceca_nitrogen_gene_list[2],"../data/huang-analysis/ceca-nitrogen-metabolism.tsv")
```

```{r rectum analysis}
rectum_protein_gene_list <- generate_kegg_gene_list(rectum_average_df, protein_digestion_and_absorption, kegg_gene_raw)
rectum_protein_more_info <- generate_more_info_table(data.frame(rectum_protein_gene_list[1]),rectum_protein_gene_list[2],"../data/huang-analysis/rectum-protein-digestion-and-absorption.tsv")

rectum_gastric_gene_list <- generate_kegg_gene_list(rectum_average_df, gastric_acid_secretion, kegg_gene_raw)
rectum_gastric_more_info <- generate_more_info_table(data.frame(rectum_gastric_gene_list[1]),rectum_gastric_gene_list[2],"../data/huang-analysis/rectum-gastric-acid-secretion.tsv")

rectum_pancreatic_acid_gene_list <- generate_kegg_gene_list(rectum_average_df, pancreatic_acid_secretion, kegg_gene_raw)
rectum_pancreatic_more_info <- generate_more_info_table(data.frame(rectum_pancreatic_gene_list[1]),rectum_pancreatic_gene_list[2],"../data/huang-analysis/rectum-pancreatic-acid-secretion.tsv")

rectum_valine_gene_list <- generate_kegg_gene_list(rectum_average_df, valine_leucine_isoleucine, kegg_gene_raw)
rectum_valine_more_info <- generate_more_info_table(data.frame(rectum_valine_gene_list[1]),rectum_valine_gene_list[2],"../data/huang-analysis/rectum-valine-leucine-isoleucine.tsv")

rectum_tyrosine_gene_list <- generate_kegg_gene_list(rectum_average_df, tyrosine_metabolism, kegg_gene_raw)
rectum_tyrosine_more_info <- generate_more_info_table(data.frame(rectum_tyrosine_gene_list[1]),rectum_tyrosine_gene_list[2],"../data/huang-analysis/rectum-tyrosine-metabolism.tsv")

rectum_tryptophan_gene_list <- generate_kegg_gene_list(rectum_average_df, tryptophan_metabolism , kegg_gene_raw)
rectum_tryptophan_more_info <- generate_more_info_table(data.frame(rectum_tryptophan_gene_list[1]),rectum_tryptophan_gene_list[2],"../data/huang-analysis/rectum-tryptophan-metabolism.tsv")

rectum_alanine_gene_list <- generate_kegg_gene_list(rectum_average_df, alanine_aspartate_glutamate, kegg_gene_raw)
rectum_alanine_more_info <- generate_more_info_table(data.frame(rectum_alanine_gene_list[1]),rectum_alanine_gene_list[2],"../data/huang-analysis/rectum-alanine-aspartate-glutamate.tsv")

rectum_nitrogen_gene_list <- generate_kegg_gene_list(rectum_average_df, nitrogen_metabolism, kegg_gene_raw)
rectum_nitrogen_more_info <- generate_more_info_table(data.frame(rectum_nitrogen_gene_list[1]),rectum_nitrogen_gene_list[2],"../data/huang-analysis/rectum-nitrogen-metabolism.tsv")
```
